apiVersion: batch/v1
kind: Job
metadata:
  name: pre-install-job
  namespace: {{ .Release.Namespace }}
  labels:
    app: my-app
spec:
  template:
    spec:
      hostNetwork: true
      serviceAccountName: helm-service-account
      containers:
        - name: pre-install-container
          image: dtzar/helm-kubectl:latest
          command: ["/bin/sh", "-c", "sh /scripts/pre-install.sh {{ .Values.provider }}"]
          volumeMounts:
            - name: script
              mountPath: /scripts
      restartPolicy: OnFailure
      volumes:
        - name: script
          configMap:
            name: pre-install-script
