{{- $resManagerConfig := (merge (dict "name" "local-resource-manager" "module" "local-resource-manager") .) -}}

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
  labels:
    {{- include "fluidos.labels" $resManagerConfig | nindent 4 }}
  name: fluidos-self-signed
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
{{- $rearManagerConfig := (merge (dict "name" "rear-manager" "module" "rear-manager") .) -}}

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
  name: {{ include "fluidos.prefixedName" $rearManagerConfig }}
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
  - {{ include "fluidos.prefixedName" $rearManagerConfig }}.{{ .Release.Namespace }}.svc
  - {{ include "fluidos.prefixedName" $rearManagerConfig }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: fluidos-self-signed
  secretName: {{ include "fluidos.prefixedName" $rearManagerConfig }}