---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate/peeringcandidate
  failurePolicy: Ignore
  name: pc.validate.fluidos.eu
  rules:
  - apiGroups:
    - advertisement.node.fluidos.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - peeringcandidates
  sideEffects: None
