apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: fluidos
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: serving-cert
  namespace: fluidos
spec:
  commonName: fluidos-validating-webhook-service.fluidos.svc
  dnsNames:
    - fluidos-validating-webhook-service.fluidos.svc
    - fluidos-validating-webhook-service.fluidos.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: serving-cert
---
apiVersion: v1
kind: Service
metadata:
  name: fluidos-validating-webhook-service
  namespace: fluidos
  labels:
    app: fluidos-validating-webhook-service
spec:
  ports:
    - port: 443
      targetPort: 9443
      protocol: TCP
      name: https-webhook
  selector:
    control-plane: fluidos-validating-webhook
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: fluidos-validating-webhook
  namespace: fluidos
  labels:
    app: fluidos-validating-webhook
  annotations:
    cert-manager.io/inject-ca-from: fluidos/serving-cert
webhooks:
  - name: pc.validate.fluidos.eu
    admissionReviewVersions: ["v1", "v1beta1"]
    clientConfig:
      service:
        name: fluidos-validating-webhook-service
        namespace: fluidos
        path: /validate/peeringcandidate
    rules:
      - apiGroups: ["advertisement.fluidos.eu"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE", "DELETE"]
        resources: ["peeringcandidates"]
    sideEffects: None
    failurePolicy: Ignore
---

