apiVersion: reservation.fluidos.eu/v1alpha1
kind: Reservation
metadata:
  name: reservation-solver-sample-2
  namespace: fluidos
spec:
  solverID: solver-sample-2
  # Set it as you want, following needs and requests in the solver.
  # Optional
  configuration:
    # Be sure to use the same type of the peeringCandidate
    type: K8Slice
    # Be sure to use values that are in the range of the peeringCandidate
    data:
      cpu: 1000m
      memory: 1Gi
      pods: "110"
  # Retrieve from PeeringCandidate chosen to reserve
  peeringCandidate:
    name: peeringcandidate-fluidos.eu-k8slice-7413576d05fe8e93c719e13eab156c5c
    namespace: fluidos
  # Set it to reserve
  reserve: true
    # Set it to purchase after reservation is completed and you have a transaction
  purchase: true
  # Retrieve from PeeringCandidate Flavor Owner field    
  seller:
    domain: fluidos.eu
    ip: 172.19.0.2:30001
    nodeID: ejbbzmacn0
  # Retrieve from configmap
  buyer:
    domain: fluidos.eu
    ip: 172.19.0.5:30000
    nodeID: e9d2mzsbcf