apiVersion: nodecore.fluidos.eu/v1alpha1
kind: Solver
metadata:
  name: solver-sample
  namespace: fluidos
spec:
  # This is the Selector used to find a Flavour (FLUIDOS node) that matches the requirements
  selector:
    # ONLY k8s-fluidos is supported at the moment
    type: k8s-fluidos
    # REMEMBER: the architecture is the one of the node, not the one of the container. Change it accordingly
    architecture: amd64
    # ONLY rangeSelector is supported at the moment
    rangeSelector:
      minCpu: "1000m"
      minMemory: "1Gi"
      minPods: "50"
  intentID: "intent-sample"
  # This flag is used to indicate that the solver should find a candidate (FLUIDOS node)
  findCandidate: true
  # This flag is used to indicate that the solver should reserve and buy the resources from the candidate (FLUIDOS node)
  reserveAndBuy: false
  # This flag is used to indicate that the solver should establish peering with the candidate (FLUIDOS node)
  enstablishPeering: false
